### ISSUE TITLE
Add some docs for `start-session` CLI ?

### ISSUE THREAD

**Issue by burnout87** [oda-hub/renku-aqs-annotation#2]
# Advances Domain

Mention the Domain this issue addresses, e.g.: 

* UX
* resilience
* community-expanding feature

**Comment by volodymyrss** [comment]
I'd leave this at low-effort and ask SDSC if maybe they potentially need or already have a feature like that

**Comment by burnout87** [comment]
Removed from this plugin, will be part of instead https://github.com/oda-hub/renku-graph-vis/
